### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by BjornSodenberg** [bs-gr/BLOG_bs-gr#15]
# **В файле search.php**

- при поиске тэгов: на странице, с выводом информации о найденных тэгах, сделать из тэгов ссылки для дальнейшего поиска.

- Учесть регистр в поисковой строке

@groneveld

**Comment by groneveld** [comment]
- [ ] при поиске тэгов: на странице, с выводом информации о найденных тэгах, сделать из тэгов ссылки для дальнейшего поиска.

**Comment by groneveld** [comment]
- [ ] Учесть регистр в поисковой строке
